### ISSUE TITLE
Xcode project file is broken

### ISSUE THREAD

**Issue by kukushi** [sushinoya/lumos#1]
![screen shot 2018-07-22 at 9 40 09 pm](https://user-images.githubusercontent.com/2424654/43046149-eb72fcbc-8df7-11e8-8dcd-4d798cfa8a62.png)

**Comment by sushinoya** [comment]
Will fix it as soon as I can. In the meantime, just add the files manually. Thanks :)

**Comment by sushinoya** [comment]
@kukushi PR #2 fixes this. Although because the pod has a dependency which is `Aspects`, I suggest you either use the `LumosDemo.xcworkspace` if you are just trying `Lumos` out or make a new project and install `Lumos` as a pod. Thanks for opening an issue :)
