### ISSUE TITLE
Crash upon accessing anything from Lumos.getAllClasses()

### ISSUE THREAD

**Issue by reenboog** [sushinoya/lumos#4]
Doing something like this:

```
let classes =  Lumos.getAllClasses().filter { b in
      return true
}
        
print(classes[0].description())
```

crashes with:

`[ description] sent to deallocated instance 0x123195e58`

The filtered array wasn't empty, sure thing.  Xcode 9.4.1.

**Comment by sushinoya** [comment]
Hmm thats odd, where are you calling the method from?

**Comment by reenboog** [comment]
Just straight in didFinishLaunchingWithOptions.

**Comment by sushinoya** [comment]
Might be a runloop issue, try:

```swift
DispatchQueue.main.async {
    let classes =  Lumos.getAllClasses().filter { b in
        return true
    }
    print(classes[0].description())
}
```

**Comment by sushinoya** [comment]
@reenboog Do let me know in the next two days if that does not fix your issue.
